### ISSUE TITLE
I keep getting: '<input>' did not match any results

### ISSUE THREAD

**Issue by bfred-it** [fisherman/z#12]
I just installed `fisher` and then `fisherman/z` but running `z anything` will always return 

```
'anything' did not match any results
```

If I open a new tab, z is no longer defined. Am I missing some steps? I also tried running `brew install z` and reinstally everything thinking that it would be a dependency but that didn't fix anything.

Incidentally `brew install z; omf install z` brings up a `_z: command not found` message so that doesn't work either. :(

**Comment by bfred-it** [comment]
Sigh, my bad. I thought that z would just be able to jump to any directory without having to visit it first.

It does work as intended. Thank you for this!

**Comment by jethrokuan** [comment]
perhaps I wasn't clear enough in the README. :smile:

**Comment by bfred-it** [comment]
It was me the one who read the first paragraph and then skipped to the other sections :D
