### ISSUE TITLE
Snippet link in readme is broken

### ISSUE THREAD

**Issue by oskarrough** [fisherman/z#16]
Hey, the snippet link in the README is a 404. Just wanted to let you know.

`curl -L git.io/snippet >> ~/.config/fish/config.fish`

**Comment by jethrokuan** [comment]
Thanks for the report, the snippet is no longer necessary, since I think it
can be expected that users have fish version >2.3 (except for Ubuntu, where
they will have to add a PPA).

I'll put up a new one just in case and fix it when I get access to my
computer. Thanks!

**Comment by jethrokuan** [comment]
That should do it (:
