### ISSUE TITLE
Unknown Command 'x86' on tab completion

### ISSUE THREAD

**Issue by sourlemon11** [fisherman/z#17]
See title.
This is from fish debug 3.
``
fish: path_get_path( 'z' )
z l fish: path_get_path( 'z' )
fish: path_get_path( 'z' )
fish: path_get_path( 'x86' )
fish: Job is constructed
fish: Unknown command 'x86'
fish: Job is constructed
fish: Job is constructed
fish: path_get_path( 'x86' )
``

**Comment by jethrokuan** [comment]
This is indeed weird. @bucaran any clue what's going on here?

**Comment by bucaran** [comment]
Hi @sourlemon11. What fish version are you running?

**Comment by sourlemon11** [comment]
The fish version is 2.3.1.

**Comment by bucaran** [comment]
This looks like a problem with fish, not z really. @sourlemon11 How about taking this to https://github.com/fish-shell/fish-shell/issues.

BTW what is `fish debug 3`?

**Comment by sourlemon11** [comment]
Yea. It might be an issue with fish. I'll try and run it later with no plugins except for Z.

Fish debug is one of the options for the command fish (fish -d 3). It's in the man docs.

**Comment by bucaran** [comment]
@sourlemon11 Thanks, just to be clear, it's not fish debug, but `fish --debug-level`.

Let me know how that goes.

**Comment by sourlemon11** [comment]
Potatoes Patatoes. Thanks @bucaran, I'll be clearer next time.

So I moved out ~/.config/fish and reinstalled the fisher function. So no omf or any other customization. I removed all the fisher plugins and reinstalled Z. And...I'm still getting the same error when pressing <tab>.

> fish: Unknown command 'x86'
> fish: x86
>        ^
> in command substitution
> 	called on standard input

FYI. I'm using this setup.
OS: Debian Jessie 64 bit
Terminal: xfce4-terminal
Fish version: 2.3.1 binary from the debian 8 repo

**Comment by bucaran** [comment]
Do you _only_ present this problem with the Z plugin? And, can you paste the entire output from your terminal? 

Thanks for your patience!

**Comment by sourlemon11** [comment]
Do you mean out of all the plugins (omf and fisher)? I've had no problems with tab completions until this plugin.

```
********@debian ~/.config> cd ~
********@debian ~> z fisfish: Unknown command 'x86'
fish: x86
      ^
in command substitution
	called on standard input

fish: Unknown command 'x86'
fish: x86
      ^
in command substitution
	called on standard input

fish: Unknown command 'x86'
fish: x86
      ^
in command substitution
	called on standard input

fish: Unknown command 'x86'
fish: x86
      ^
in command substitution
	called on standard input

/home/********/
```

fish -d 3
```
********@debian ~> zfish: path_get_path( 'z' )
 fisfish: path_get_path( 'z' )
 fish: path_get_path( 'x86' )
 fish: Job is constructed
 fish: Unknown command 'x86'
 fish: Job is constructed
 fish: Job is constructed
 fish: path_get_path( 'x86' )
 fish: Job is constructed
 fish: Unknown command 'x86'
 fish: Job is constructed
 fish: Job is constructed
 /home/********/fish: path_get_path( 'z' )
```

**Comment by bucaran** [comment]
Hi @faho! The `x86` message looks like something only fish could log out. Do you have any idea what could be causing this?

**Comment by jethrokuan** [comment]
FWIW [here's](https://github.com/fisherman/z/blob/master/functions/__z_add.fish#L17-L19) where I add tab completions for the directories:


I doubt it would cause a problem like that though.

**Comment by sourlemon11** [comment]
Well the function is being called from [fish-shell/src/path.cpp](https://github.com/fish-shell/fish-shell/blob/21fc2decd741d3a18c88445e11de8860148060d0/src/path.cpp#L24). I'm not sure if something is being incorrectly called or it's an issue with the function itself.

**Comment by bucaran** [comment]
@jethrokuan In the code, make sure "$path" holds an actual value. We know very well that's a common source of bugs in shell.

**Comment by jethrokuan** [comment]
@bucaran it's set to `$PWD`, which should be universally available

**Comment by faho** [comment]
This is https://github.com/fish-shell/fish-shell/issues/952, which is supposed to be fixed in fish 2.3.0.

The issue was that the `cd` completion would call `eval` on the path, which would try to execute a "(x86)" as a command substitution. It seems this has reappeared here somehow.

@sourlemon11: Can you check that the first `cd.fish` in $fish_complete_path doesn't have "eval" in it anymore? If it does, you have an older version and need to clean your installation.

Or maybe this script includes an old copy of that one? Or calls `eval` otherwise in a completion?

**Comment by jethrokuan** [comment]
I may be wrong, but I'm quite sure that `z` doesn't call eval to create completions. It does, however, depend on `cat`, `sed`, and `tr`. 

```
find $fish_complete_path -name "cd.fish"  
```

this will find you `cd.fish`, for your convenience.

**Comment by sourlemon11** [comment]
Ok. So I followed @faho advice and checked for eval in cd.fish. 
```
for i in (locate 'cd.fish')
        echo ---------------------$i------------------
        ag 'eval' $i
end

---------------------/home/********/.local/share/fish/generated_completions/dhcpcd.fish------------------
---------------------/home/********/.local/share/fish/generated_completions/mtx-fcd.fish------------------
---------------------/home/********/.local/share/omf/pkg/omf/functions/cli/omf.cli.cd.fish------------------
---------------------/home/********/.local/share/omf/pkg/omf/functions/packages/omf.packages.cd.fish------------------
---------------------/home/********/tmp/functions.bak/fcd.fish------------------
---------------------/usr/share/fish/completions/cd.fish------------------
---------------------/usr/share/fish/functions/__fish_complete_cd.fish------------------
---------------------/usr/share/fish/functions/cd.fish------------------
```
No dice. So I moved out ~/.config/fish again and created a fresh fish dir, added config.fish and the fisher function, fisher rm z, fisher z. Now it appears to work for some reason!? I'm trying to recreate the issue but I'm just left scratching my head wondering what file in my ~/.config/fish was causing issues.

**Comment by jethrokuan** [comment]
@sourlemon11 sorry for the late reply. I'm glad all your issues have been resolved.

Keep the issue in mind, and when it pops up again let us know ya?
