### ISSUE TITLE
z causes cd command to throw errors

### ISSUE THREAD

**Issue by kmiasko** [fisherman/z#18]
Because of `&` sign in one of the completion paths (i assume) `z` causes a `cd` command to throw some errors messing all the terminal.

`kmiasko ~/.c/fish λ cd conf.d/`
`kmiasko ~/.c/f/conf.d λ cd ..`
`kmiasko ~/.c/fish λ fisher install z`
`Installing 1 plugin/s`
`OK Fetch z github.com/fisherman/z`
`Installing 1 dependency`
`OK Copy getopts`
`Done in 1s 725ms`
`kmiasko ~/.c/fish λ cd conf.d`

complete: Completion [huge list of directories] contained a syntax error
Expected an argument, but found a '&'
complete: [huge list of directories] 

`kmiasko ~/.c/fish λ`

**Comment by jethrokuan** [comment]
Good catch. This also fails for directories with spaces.

I should wrap the completions in double quotes. I shall see what I can do.

**Comment by jethrokuan** [comment]
@kmiasko it should work now. 

Try updating z with `fisher u z` and report back if it's successful :smile:

**Comment by kmiasko** [comment]
@jethrokuan Works like a charm, thanks.

**Comment by jethrokuan** [comment]
:+1:  closing as resolved.
