### ISSUE TITLE
Clean Z_DATA selectively

### ISSUE THREAD

**Issue by vishthemenon** [fisherman/z#19]
Sometimes, jumps to certain directories become erroneous after extended periods of usage. Currently, the only way to fix it is by going to the "~/.z" file and removing every line referencing to the directory or running `z --clean` to wipe out Z_DATA which will result in loss of data for other directories.

Feature Request:

`z [-c --clean] <directory_name>`
eg.
`z --c documents` will remove all the entries in the .z file that matches 'documents'

**Comment by jethrokuan** [comment]
I'm trying to understand your use case here. Would it be better if it were able to clean up directories that no longer exist?

z uses the "last accessed" heuristic, so folders that have not been recently accessed would be necroed and should rank low during completion.

**Comment by jethrokuan** [comment]
bump?

**Comment by vishthemenon** [comment]
For the most part, z would jump to the right folder. However, recently, I have been facing this issue.

eg. 

I have following folder structure

~/Documents
~/Documents/Projects

Most of the time I in the projects folder and sometimes in the documents folder.
So when I `z projects` it jumps to `~/Documents/Projects` which is perfect. However, when I `z documents`, it goes to `~/Documents/Projects` instead of what I want which is `~/Documents`.

I did not really get much time to take a look under the hood for z. Perhaps, my feature request does not actually solve the problem I have. It is only quick, easy temp. fix.

**Comment by jethrokuan** [comment]
That's unfortunately the way `z` works: it matches the full string of the directory. You can blacklist a certain directory if you don't want it to be indexed. I could consider changing the implementation of z to match only the folder name and not the path, but I can foresee certain cases where that would be undesirable.

In general for common folders like `~/Documents`, using z to navigate to them would not be ideal. What you want is really something like [bashmarks](https://github.com/huyng/bashmarks). Let me know if you need this in fish, and I'll look into it.

**Comment by jethrokuan** [comment]
Closing in favour of #20
