### ISSUE TITLE
Output redirection not working

### ISSUE THREAD

**Issue by jlesquembre** [fisherman/z#21]
I think is related to awk.

Try:

`z -l > file`

file is empty and output is printed to stdout

**Comment by jethrokuan** [comment]
Thanks for the report, and your intuition is right. Should be fixed with ca4b1a996e6d211e882d937602b35f81b87c7c41.

I'll probably need to take some time to clean up the awk code.

**Comment by jlesquembre** [comment]
Thanks for the fix, works great.
