### ISSUE TITLE
error message in startup screen

### ISSUE THREAD

**Issue by seagle0128** [fisherman/z#24]
I am using fish 2.3 + fisherman in cygwin on Windows 7. Recently I upgraded fisherman and z plugin, and encountered this error while starting fish shell every time. Please check.
 
``` shell
~/.config/fish/functions/__z_complete.fish (line 1): cat $Z_DATA | sed -e "s/|.*//" -e "s/^.*\$/\"&\"/g" | tr '\n' ' '
                                                                   ^
in command substitution
        called on line 0 of file ~/.config/fish/functions/__z_complete.fish

in function “__z_complete”
        called on line 32 of file ~/.config/fish/conf.d/z.fish

from sourcing file ~/.config/fish/conf.d/z.fish
        called on line 207 of file /usr/share/fish/config.fish

from sourcing file /usr/share/fish/config.fish
        called during startup
```

**Comment by jethrokuan** [comment]
Hi Vincent,

This is due to a recent change I made. Can I check if you cygwin comes with
`tr` and `sed`. This is likely the issue.

**Comment by jethrokuan** [comment]
sorry, just looked through this proper on a laptop. could you try typing `type sed`  in your prompt?

**Comment by seagle0128** [comment]
Thanks. The result is

```shell
sed is /bin/sed
```

**Comment by seagle0128** [comment]
Thanks. Sed version is 4.2.2.
The result is

```shell
sed is /bin/sed
```

**Comment by jethrokuan** [comment]
just to double confirm can you type `cat $Z_DATA | sed -e "s/|.*//" -e "s/^.*\$/\"&\"/g" | tr '\n' ' '`. Just trying to isolate the problem to this line.

**Comment by seagle0128** [comment]
```shell
 /c/c/U/zhangv11> cat $Z_DATA | sed -e "s/|.*//" -e "s/^.*\$/\"&\"/g" | tr '\n' ' '
"/home/zhangv11/.ssh" "/cygdrive/c/Users/zhangv11/Documents/Work" "/home/zhangv11/.cache" "/home/zhangv11/.config/fisherman/pwd_info" "/home/zhangv11/.config/fisherman/z" "/cygdrive/c" "/cygdrive/c/Users/zhangv11/Documents/src/postreview" "/home/zhangv11/.emacs.d" "/cygdrive/c/Users/zhangv11/Documents/work/Innovation" "/home/zhangv11/.config/fisherman/host_info" "/cygdrive/c/Users/zhangv11/AppData" "/cygdrive/c/Users/zhangv11/Documents/src/Panda1/scheduler/bin" "/home/zhangv11/.config/fisherman/getopts" "/cygdrive/c/Users/zhangv11/.config" "/" "/home/zhangv11/.config/fisherman/last_job_id" "/home/zhangv11/.config/fisherman/git_util" "/cygdrive/c/Users/zhangv11/AppData/Roaming/.emacs.d/lisp" "/cygdrive/c/Users/zhangv11/Documents/src/Panda1" "/cygdrive/c/Users/zhangv11/Documents/Work/Innovation" "/cygdrive/c/Users/zhangv11/AppData/Roaming/org" "/home/zhangv11/.emacs.d/elpa" "/home/zhangv11/.cache/fisherman" "/cygdrive/c/Users/zhangv11/AppData/Roaming/.emacs.d/.git" "/home/zhangv11/autojump/tools" "/home/zhangv11/.config/fish/conf.d" "/home/zhangv11/autojump" "/cygdrive/c/Users/zhangv11/Documents/src/Panda1/scheduler" "/cygdrive/c/Users/zhangv11/AppData/Roaming" "/home/zhangv11/.config/fish/functions" "/home/zhangv11/.config/fisherman/pwd_is_home" "/home/zhangv11/.config/fish" "/home/zhangv11/.local/share/fish" "/cygdrive/c/Users/zhangv11/Documents/src" "/home/zhangv11/.config/fisherman/humanize_duration" "/cygdrive/c/Users/zhangv11/Documents/Work/Innovation/Baymax/Baymax" "/cygdrive/c/Users/zhangv11/AppData/Roaming/.emacs.d" "/home/zhangv11/.config/fisherman/metro" "/cygdrive/c/Users/zhangv11/.config/fish" "/home/zhangv11/.local" "/cygdrive/c/Users/zhangv11/Documents/src/Panda1/scheduler/bin/scheduler" "/cygdrive/c/Users/zhangv11/Documents/Work/Innovation/Baymax" "/cygdrive/c/Users/zhangv11/Documents" "/home/zhangv11/.config" "/home/zhangv11/example" "/home/zhangv11/.config/fisherman" "/home/zhangv11/.local/share" "/home/zhangv11/.config/fisherman/segment" "/cygdrive/c/cygwin64" "/home/zhangv11/.config/fish/completions" "/cygdrive/c/Users/zhangv11/Downloads" "/cygdrive/c/Users/zhangv11" "/cygdrive/c/Users/zhangv11/Documents/work" 
```

**Comment by jethrokuan** [comment]
@jbucaran any clue what's going on? looks like sed and tr are both present.

**Comment by jbucaran** [comment]
@seagle0128 Does the problem persists? Is Z_DATA empty?

That would explain the first error.

**Comment by jethrokuan** [comment]
the output of the line shows that it isn't empty though

**Comment by seagle0128** [comment]
@jbucaran The issue persists. and Z_DATA is not empty.

**Comment by jbucaran** [comment]
@seagle0128 Interesting! Are you signed up to the fisherman team on Slack? If you are I could live assist you whenever both of us have time again.

If you sign up, I'll ping you when I am available to see if I catch you.

→ [join.fisherman.sh](https://fisherman-wharf.herokuapp.com/)

**Comment by jethrokuan** [comment]
I'm going to close this for now, feel free to reopen if the issue persists.

**Comment by seagle0128** [comment]
Recently I noticed this issue is related to Cygwin itself. The PATH is incorrect while loading fisher plugins. If using absolute path (e.g. /bin/sed), the error disappears. I think it's about env loading issue. Your opinion?

**Comment by jethrokuan** [comment]
it's not using absolute paths now? It's hard to comment on the issue, since you do have the tools required, `tr` and `sed` and this has nothing to do with how fish loads the plugins.

**Comment by jbucaran** [comment]
Hey @seagle0128 Can you share your config.fish?

**Comment by seagle0128** [comment]
Hi @jbucaran, there is no specific configurations in config.fish. The issue exists even if the config.fish is empty.

Hi @jethrokuan I'm going to reinstall Cygwin on Windows 7. For now I have to set PATH=/bin to start the console to load z plugin correctly. z doesn't use absolute paths in __z_complete.fish.

**Comment by jethrokuan** [comment]
__z_complete reads from your `Z_DATA` file, which contains absolute paths.

**Comment by seagle0128** [comment]
@jethrokuan  I mean "cat", "tr" and "sed" cannot be found unless using "/bin/cat", "/bin/tr" and "/bin/sed".

**Comment by jethrokuan** [comment]
That could be an issue of fish running in cygwin, but its unlikely.

**Comment by jbucaran** [comment]
@seagle0128 Could this be a problem with how fish handles $PATH as an array (instead of a string:string:...)?

**Comment by seagle0128** [comment]
@jbucaran I don't think so. No idea of it. I install Cygwin on Windows 10 for my another laptop. No such an issue with the same configuration.

**Comment by jethrokuan** [comment]
From what I see `/bin` is not in `$PATH` which is why absolute paths are required to access tr and sed. However, this conflicts with the fact that `type sed` seems to find it at `/bin/sed`, so this seems to be either a cygwin or fish issue.

**Comment by seagle0128** [comment]
@jethrokuan you got the point. Thanks!

**Comment by jethrokuan** [comment]
@seagle0128 no problem, feel free to reach out to us if you face any more issues.

**Comment by ntsuji** [comment]
I am sorry to bring up the old issue, but I am having same problem.

When I add ``/bin`` to the Windows's system environment variable ``PATH``, or edit ``~/.config/fish/functions/__z_complete.fish`` adding ``/bin/`` to ``cat``, ``sed`` and ``tr``, the error disappear.

**Comment by jethrokuan** [comment]
You should have `/bin` in `PATH` so that `cat`, `sed` and `tr` can be accessed without stating its path. I don't think that's a unreasonable requirement.
