### ISSUE TITLE
Chinese language support

### ISSUE THREAD

**Issue by TangMonk** [fisherman/z#25]
error like following image if history contain Chinese words:

![image](https://cloud.githubusercontent.com/assets/3498786/20585869/a4788da4-b239-11e6-8fd7-70223dca2e46.png)

Several situations:

1. I remove line `/Users/tangmonk/Dropbox (个人)|1|1479957811` in `~/.z` works again
2. change `Dropbox (个人)` to `Dropbox 个人` works, it same the brackets problems

**Comment by jethrokuan** [comment]
Could you `cd` into the `个人` folder and show me the results of `dirname (status -f)`?

**Comment by TangMonk** [comment]
@jethrokuan 

just print a dot

```
➜  Dropbox (个人) dirname (status -f)
.
```

**Comment by TangMonk** [comment]
Hi @jethrokuan , Are your from Singapore? I have heard that many Singaporeans use Chinese.

**Comment by jethrokuan** [comment]
@TangMonk yes I am, but most of us use English as the dominant language, especially those who do programming. Can you print `$PWD` in the same directory? I misread my own code :P

**Comment by TangMonk** [comment]
```
➜  Dropbox (个人) echo $PWD
/Users/tangmonk/Dropbox (个人)
```

**Comment by jethrokuan** [comment]
right, fish uses the bracket syntax for commands, there will be a need for escaping. This is not a chinese character support issue. Odd that no one has picked this up yet.

**Comment by jethrokuan** [comment]
I actually can't replicate your issue:

```
~ 
❯ cat ~/.z                                                                                                  08:49:52 PM 
/home/jethro/Dropbox (个人)|3|1480078190

~ 
❯ z drop                                                                                                    08:50:31 PM 

~/Dropbox (个人) 
❯  
```

**Comment by TangMonk** [comment]
sorry for late comment, I using `fisher update z` to update, it works again
