### ISSUE TITLE
~/.z file changes owner to root after run `z` in `sudo fish`

### ISSUE THREAD

**Issue by explosic4** [fisherman/z#26]
After run `z` command in `sudo fish` mode, the `~/.z` file will change owner to root, and I got `permission denied` error when I back to normal mode.

```awk: ~/.config/fish/functions/z.awk:34: fatal: cannot open file '~/.z\' for reading (Permission denied)```

**Comment by jbucaran** [comment]
@explosic4 What should z do in this case then?

**Comment by explosic4** [comment]
@jbucaran maybe change the permission mode of `~/.z` file to `-rw-rw-rw-` so the user can access it after leaving `sudo` mode.

Currently not only the owner is changed after `sudo` mode, the permission mode is also changed to `-rw-------`

**Comment by jbucaran** [comment]
@explosic4 I don't think z should be responsible of changing file permissions. What do you think @jethrokuan?

**Comment by jethrokuan** [comment]
@jbucaran @explosic4 it shouldn't change file permissions. Perhaps the temp file was created with root permissions only: this will need to be corrected. I'll need to take a look at the underlying code again (its been a while). Thanks for the report.

**Comment by jethrokuan** [comment]
I'm curious how you installed fisherman and z, because for me it's only available for the current user, and not available with `su` or `sudo fish`.

**Comment by explosic4** [comment]
@jethrokuan  I installed z with `fisher z`, but I am not sure how I installed fisherman.

**Comment by jethrokuan** [comment]
@explosic4 reviving this again. What do you think the appropriate behaviour should be? The file can be created with rw permissions for all users and groups. I'd much rather leave these things to the OS.

**Comment by explosic4** [comment]
Instead of replacing the `$Z_DATA` file with the new file, I think we can just overwrite its content:
```bash
cat $tmpfile > $Z_DATA
rm $tmpfile
```
This will leave the permission and owner unchanged and solve the problem.

**Comment by jethrokuan** [comment]
@explosic4 I like this approach. Great suggestion!

**Comment by jethrokuan** [comment]
https://github.com/fisherman/z/commit/c323913826a90b7ccc82a9c4c0297b1544b560fa should've resolved it I think.
