### ISSUE TITLE
auto complete functionality not behaving correctly

### ISSUE THREAD

**Issue by amir20** [fisherman/z#30]
Hello there,

This might not be a bug. I want to make sure I am understanding how `z` should behave correctly. 

## Problem
`z <tab>` doesn't sort by frequency. 

## Example
`z phantom` yields to `~/Workspace/phantomjs-node`.

`z phantom<tab>` shows 
```
/Users/amirraminfar/Desktop/phantom-docker  /Users/amirraminfar/Desktop/test_phantom      /Users/amirraminfar/Workspace/phantomjs-node/examples  /Users/amirraminfar/Workspace/phantomjs-node/src         
/Users/amirraminfar/Desktop/phantom_test    /Users/amirraminfar/Workspace/phantomjs-node  /Users/amirraminfar/Workspace/phantomjs-node/lib       /Users/amirraminfar/Workspace/phantomjs-node/src/__test__
```

As you can see, `phantom-docker` shows up first. Shouldn't `phantomjs-node` be the first on the list?

**Comment by jethrokuan** [comment]
hi @amir20,

If you take a look at https://github.com/fisherman/z/blob/master/functions/__z_complete.fish, you'll notice that no processing is being done to produce completions.

I'm afraid that calling the awk script upon `<tab>` would be too involved, and wish to keep this simple.

**Comment by amir20** [comment]
Hm ok. That makes sense. You can close. Thanks!
