### ISSUE TITLE
Improve startup time

### ISSUE THREAD

**Issue by aristidesfl** [fisherman/z#31]
During a chat on Gitter fish-shell/fish-shell , [Kurtis Rader](https://github.com/krader1961) - one of the core contributors - [suggested](https://gitter.im/fish-shell/fish-shell?at=58e843c38bb56c2d1187db3e) that the startup time of this plugin could be improved by modifying [this line](https://github.com/fisherman/z/blob/1.1/functions/__z_complete.fish#L2): 

``` 
 set -l __z_marks (cat $Z_DATA | sed -e "s/|.*//" -e "s/^.*\$/\"&\"/g" | tr '\n' ' ')
```

> Looking at your profile the most expensive item is the (cat $Z_DATA | sed -e "s/|.*//" -e "s/^.*\$/\"&\"/g" | tr '\n' ' ') subcommand. You can speed that up by 1) removing the useless use of cat, and 2) switching the sed and tr to the string builtin.

**Comment by jbucaran** [comment]
Definitely room for improvement there, here is a start:

```
set -l __z_marks (awk '

' < $Z_DATA)
```

**Comment by jethrokuan** [comment]
Agreed. I'll take a look at it at the start of May, once my exams are over. Feel free to send a PR though. 😄

**Comment by jethrokuan** [comment]
Just pushed a change, should hopefully solve this issue: https://github.com/fisherman/z/commit/748fc0fd8119515f65e073cc08dba5d3db829eb5

**Comment by aristidesfl** [comment]
Nice. did you measure the time difference? is awk faster than the string builtin which kurtis suggested?

**Comment by jbucaran** [comment]
@aristidesfl The string builtin is supposed to be faster than awk for most simple to "intermediate" tasks. But as soon as you mix it with any fish construct, if/while, etc., expect a dramatic performance drop.

**Comment by jethrokuan** [comment]
Also, we're dealing with structured data here, so awk fits the task really well.

**Comment by jethrokuan** [comment]
Closing as resolved.

**Comment by aristidesfl** [comment]
@jbucaran implementation using string:

```
string replace -r '(^[^|]*)\|.*$' '"$1"' < $Z_DATA | string join ' '
```

**Comment by aristidesfl** [comment]
Do yo even need to remove the newlines? https://github.com/fisherman/z/commit/748fc0fd8119515f65e073cc08dba5d3db829eb5#diff-8acb27c0d8c9f82638db3460675b73c7R2 produces a different result than the original command doesn't it?

**Comment by jethrokuan** [comment]
Re newlines, not needed; turns out `complete` handles newlines as well.

Awk version:
```
0.07user 0.00system 0:00.09elapsed 82%CPU (0avgtext+0avgdata 5844maxresident)k
0inputs+0outputs (0major+5078minor)pagefaults 0swaps
```

string version:
```
0.07user 0.00system 0:00.09elapsed 82%CPU (0avgtext+0avgdata 6000maxresident)k
0inputs+0outputs (0major+4834minor)pagefaults 0swaps
```

I actually have no idea how to interpret this data , but it seems that they're practically equivalent.

**Comment by aristidesfl** [comment]
Maybe time is not precise enough to measure this?

**Comment by aristidesfl** [comment]
@jethrokuan does it also handle unescaped paths with spaces and other strange characters?

**Comment by aristidesfl** [comment]
It turns out current and previous versions are broken if any path contains a `"` character. Previous version might support single quote characters `'`.

Opened a PR with fix using string builtin.
