### ISSUE TITLE
A single ' in a visited path causes autocomplete error

### ISSUE THREAD

**Issue by wgslr** [fisherman/z#33]
Steps to reproduce:
create a directory with a name containing single apostrophe, eg.
```fish
mkdir "andy's dir"
cd "andy's dir"
```

Now every time you change directories (`cd`) there is a huge error message 
> complete Completion '...' contained a syntax error. Unexpected end of string, quotes are not balaned

**Comment by jethrokuan** [comment]
hi @wgslr, could you update z with `fisher z`? I'm following your steps, and can't reproduce with the latest `z`.

**Comment by wgslr** [comment]
Thank you @jethrokuan, updating everything whith `fisher up` indeed solved the issue. Sorry for bothering you!
For my defence, it was a problem with z for sure since deleting corresponding line from '~/.z' would solve the problem temporarily.

**Comment by jethrokuan** [comment]
no issue! I think this was fixed recently as well, with one of the latest PRs.
