### ISSUE TITLE
No jump to shortest matching path

### ISSUE THREAD

**Issue by jnns** [fisherman/z#38]
[rupa/z](https://github.com/rupa/z) provides the following feature which apparently is also implemented in [fisherman/z](https://github.com/fisherman/z) but does not work for me: 

> Common: When multiple directories match all queries, and they all have a common prefix, z will cd to the shortest matching directory, without regard to priority. 

# Test scenario

```bash
> mkdir -p foo/bar/a
> mkdir -p foo/bar/b
> cd foo/
> cd bar
> cd a
> cd ../b
> z -l
4          /home/jnns/foo/bar/b
4          /home/jnns/foo/bar/a
4          /home/jnns/foo/bar
> z -e foo
/home/jnns/foo/bar
```

I expect the directory to be changed to `foo` but I'm taken to the most *frecent* entry instead – not the shortest match.

**Comment by jethrokuan** [comment]
@jnns did you confirm the same behaviour to exist in rupa's z? I don't think you'll ever be taken to `/foo` because it's not explicitly in the `z` file, and `z` only ever brings you to directories that are explicitly listed in the file.

**Comment by jnns** [comment]
@jethrokuan I'm not sure whether a line went missing during copy'n'paste but I retried the following:

```bash
> cd foo/bar
> z -l
8          /home/jnns/foo/bar/b
8          /home/jnns/foo/bar/a
8          /home/jnns/foo/bar
8          /home/jnns/foo
> z -e foo
/home/jnns/foo/bar
```

This is what happens with rupa's z: 

```
> cp ~/.local/share/z/data ~/.z
> z -l
common:    /home/jnns/foo
8          /home/jnns/foo
8          /home/jnns/foo/bar
8          /home/jnns/foo/bar/a
8          /home/jnns/foo/bar/b
> z -e foo
/home/jnns/foo
```

The behavior differs in the two implementations. Rupa's approach comes in handy when you want to return to a project root quickly, for example.

**Comment by jethrokuan** [comment]
I can see where you're coming from. I'll look into it!

**Comment by jnns** [comment]
If anyone else is having this problem: a workaround I found useful is to use 

    z 'foo$'

This makes use of a regular expression that matches for a line end.

**Comment by jethrokuan** [comment]
@jnns let me know if it doesn't work. my primitive testing tells me this works.

**Comment by jnns** [comment]
Thank you for your efforts in fixing this! Seems to work flawlessly now.

**Comment by jethrokuan** [comment]
awesome!
