### ISSUE TITLE
Since latest update ~/.z seems to be ignored

### ISSUE THREAD

**Issue by externl** [fisherman/z#43]
Just updated to the latest commit. My `~/.z` file is full of stuff.

```
cat .z | wc -l
     140
```

Howerver, `z` seems have started from scratch. `z --list` just shows the one directory I cd' to after updating, likwise for `z dir`.  Has the z file moved?

EDIT: Looking at the last commit, maybe it's using a new format and the old file was not migrated?
EDIT 2: Entries in `~/.z` appear consistent.

**Comment by jethrokuan** [comment]
Hi, looks like it's this commit: https://github.com/fisherman/z/commit/c69b75ca43eb5e0c44f02e683029b1932fe0be33

The default z file has moved to a location more consistent with best practices. you can set `$Z_DATA` to point back to `~/.z` if you wish.

**Comment by externl** [comment]
Where is the new location? `z --help` still indicates `~/.z`.

**Comment by jethrokuan** [comment]
could you `echo $Z_DATA`? also, `z --list` is not a verbatim print of `$Z_DATA`, now that there's some handling of common paths.

**Comment by externl** [comment]
```
❯ echo $Z_DATA
/Users/joe/.z
```

**Comment by jethrokuan** [comment]
I think it might be an issue with `z --list`, let me take a look into this.

**Comment by externl** [comment]
Regular jumping isn't working for me either.

**Comment by jethrokuan** [comment]
Hmm okay, I can't replicate that, but let me revert the latest commit and
look into it further.

**Comment by jethrokuan** [comment]
@externl update to latest commit and let me know if it works now?

**Comment by externl** [comment]
Ok, so I did a `fisher update` and now `$Z_DATA` is in the new location....

**Comment by externl** [comment]
I copied `~/.z` to `~/.local/share/z/data` and it's working now.

**Comment by externl** [comment]
Somehow `~/.z` was destroyed. It now only contains 6 lines. Before the update it was over 100.

**Comment by jethrokuan** [comment]
There's nothing this destructive in the plugin I believe. Unless you ran `z --clean` or `z --purge`.

**Comment by jethrokuan** [comment]
I'll close it for now, let me know if it comes up again.

**Comment by externl** [comment]
Will do, you can probably un-revert your commit. TBO I have no idea why the env was so messed up.

**Comment by jethrokuan** [comment]
I made a mistake in the `z --list`, should be fixed in https://github.com/fisherman/z/pull/44

**Comment by externl** [comment]
After running `fisher update`, my z data file seems to have been erased again!

**Comment by jethrokuan** [comment]
can you walk through the same steps above (e.g. printing $Z_DATA), I can't help you without any information

**Comment by externl** [comment]
Ok, I've figured out how to reproduce.

Run `fisher update`, and while it's running open a new tab/window. In this new window z's data file will have been re-initialized.

**Comment by jethrokuan** [comment]
This sounds like an issue with `fisherman` and not this plugin. Don't think this is a huge deal though.
