### ISSUE TITLE
Impossible to capture output from --list

### ISSUE THREAD

**Issue by externl** [fisherman/z#47]
This should return nothing:
```
❯ z --list fisherman >/dev/null ^/dev/null
2          /Users/joe/.config/fish/fisherman
2          /Users/joe/.config/fish/fisherman/conf.d
2          /Users/joe/.config/fish/fisherman/functions
6          /Users/joe/.config/fisherman
44         /Users/joe/.config/fisherman/await
44         /Users/joe/.config/fisherman/docker-completion
44         /Users/joe/.config/fisherman/fzf
44         /Users/joe/.config/fisherman/fzy
44         /Users/joe/.config/fisherman/get
44         /Users/joe/.config/fisherman/getopts
48         /Users/joe/.config/fisherman/last_job_id
48         /Users/joe/.config/fisherman/menu
48         /Users/joe/.config/fisherman/spin
52         /Users/joe/.config/fisherman/pure
52         /Users/joe/.config/fisherman/z
```
This makes it impossible to do something like:
```
z --list fisherman | grep docker-completion
```

Works fine with echo.
```
❯ z -e fisherman | grep z
/Users/joe/.config/fisherman/z
```

Likewise it seems output of `--list` is sent to `stderr`.

```
❯ /usr/local/bin/fish -l -c 'z --list fisherman' > /dev/null
2          /Users/joe/.config/fish/fisherman
2          /Users/joe/.config/fish/fisherman/conf.d
2          /Users/joe/.config/fish/fisherman/functions
6          /Users/joe/.config/fisherman
44         /Users/joe/.config/fisherman/await
44         /Users/joe/.config/fisherman/docker-completion
44         /Users/joe/.config/fisherman/fzf
44         /Users/joe/.config/fisherman/fzy
44         /Users/joe/.config/fisherman/get
44         /Users/joe/.config/fisherman/getopts
48         /Users/joe/.config/fisherman/last_job_id
48         /Users/joe/.config/fisherman/menu
48         /Users/joe/.config/fisherman/spin
52         /Users/joe/.config/fisherman/pure
52         /Users/joe/.config/fisherman/z

❯ /usr/local/bin/fish -l -c 'z --list fisherman' ^ /dev/null
```

Afaict only `common: ` should be sent to `stderr`

**Comment by jethrokuan** [comment]
This is likely because it is awk that is doing the printing. I'll look into it when I find the time.

**Comment by externl** [comment]
I haven't figured out the specifics of exactly why rupa z does it, but I see where it comes from.

The main stderr redirect:
https://github.com/rupa/z/blob/master/z.sh#L150
https://github.com/fisherman/z/blob/master/functions/z.awk#L12

```
        cmd = "sort -n >&2"
        for( x in matches ) {
            if( matches[x] ) {
                printf "%-10s %s\n", matches[x], x | cmd
            }
        }
```

Howerver, in rupa z there is also:
https://github.com/rupa/z/blob/master/z.sh#L214
```
alias ${_Z_CMD:-z}='_z 2>&1'
```
Which redirects `stderr`  into `stdout`.

It's not obvious to to me yet why rupa/z is designed this way.

**Comment by externl** [comment]
The other issue, where output of `--list` can't be captured is caused by https://github.com/fisherman/z/blob/master/functions/__z.fish#L59

```
 set target (command awk -v t=(date +%s) -v list="$list" -v typ="$typ" -v q="$arg" -F "|" -f $z_path/z.awk "$Z_DATA")
```

This ends up printing to `stderr` and and `target` is empty.

**Comment by jethrokuan** [comment]
Your comment sounds like a reasonable solution. A PR would be much appreciated!

**Comment by externl** [comment]
Looking at this line https://github.com/fisherman/z/blob/master/functions/__z.fish#L63
```
if test "$list" = "list"
    echo "$target" | tr ";" "\n" | sort -nr
    return 0
end
```
I don't how there would ever be any `;`'s, and list should now already be sorted from the updated awk. Also, this section sorts in reverse, where the awk list sort does not.

Currently, this section is skipped because `target` is empty. Can we remove this section now?

**Comment by jethrokuan** [comment]
yes, there should probably be a test case for this as well the `list` flag as well

**Comment by externl** [comment]
PR submitted. I had to rework the main `__z` a little to better handle `--list` mode printing the common path to `stderr`.
