### ISSUE TITLE
Error: argparse?

### ISSUE THREAD

**Issue by rdegges** [fisherman/z#55]
I just installed this plugin with fisher, and I get the following output:

```
$ z
No command 'argparse' found, did you mean:
 Command 'augparse' from package 'augeas-tools' (main)
argparse: command not found
~/.config/fish/functions/__z.fish (line 17): 
    argparse $options -- $argv
    ^
in function “__z”
	called on line 25 of file ~/.config/fish/conf.d/z.fish

in function “z”
	called on standard input

'' did not match any results⏎
```

Any idea? I'm running ubuntu latest.

**Comment by jethrokuan** [comment]
you're likely to be running a version of fish that does not have argparse. I suggest upgrading your fish version to at least 2.7.0. In the case of ubuntu, that would involve adding the appropriate PPA.

If you don't want to upgrade fish, you can install the legacy version of this plugin: `fisher z@pre27`

**Comment by aswinmohanme** [comment]
Can confirm on Fedora 27, the updates are still to reach the repos

**Comment by ElijahLynn** [comment]
@jethrokuan solution to run `fisher z@pre27` works, in my case I am on fish 2.3.1 on RHEL7.
