### ISSUE TITLE
-x option

### ISSUE THREAD

**Issue by peey** [fisherman/z#59]
From [rupa/z](https://github.com/rupa/z)

     -x     remove the current directory from the datafile

Use Case: Let's say I've moved the directory from one place to another. It'll take some time for z to learn that the new directory is the path I want to go to, especially if the old path was very frequently used. Instead, if I have an option to nuke the current director from the datafile, it can go to the next best match.

Another [use case](https://github.com/rupa/z/issues/208#issuecomment-317659012).

**Comment by jethrokuan** [comment]
am a little busy now, I'll add this in in a few weeks.
