### ISSUE TITLE
z does not check if directory exists before trying to cd into it

### ISSUE THREAD

**Issue by peey** [fisherman/z#60]
If I delete a directory I expect it to be gone from z's list too. Perhaps the easy way of doing this would be to check if the directory exists before cding to it, and if it doesn't then trying the next best match.

Steps to reproduce:
 1. `mkdir random-folder-name`
 2. `cd random-folder-name`
 3. `cd ../`
 4. `z random-folder-name` to see if it works
 5. `rmdir random-folder-name`
 6. `z random-folder-name`

After running step 6, you'll see an error like

    cd: The directory “/path/to/random-folder-name” does not exist

**Comment by jethrokuan** [comment]
This logic flow adds quite a bit of complexity, which I want to avoid in shell scripts. Unlike changing directories, removing directories does not have a hook that fish shell can listen on. I'm closing this as a `wont-fix` for now, but I'm open to PRs that can achieve this with simplicity.
