### ISSUE TITLE
Z_CMD setting doesn't work

### ISSUE THREAD

**Issue by laughedelic** [fisherman/z#7]
In the `~/.config/fish/config.fish`:

```fish
set -U Z_CMD "j"
```

In the fish:

```
❯ echo $Z_CMD
j

❯ j foo
fish: Unknown command 'j'
```

What am I doing wrong? I think, it has changed since the fisher 2.0 upgrade.

**Comment by laughedelic** [comment]
Actually `z` kind of breaks all the time. If I reinstall it, it works, but if I open an new fish session, it doesn't work there.

**Comment by laughedelic** [comment]
It was my problem with upgrading fisherman to 2.+. Solved.

**Comment by jethrokuan** [comment]
@laughedelic yup, I think what happened was that you were missing the `conf.d` snippet.
